"use client"

import { useState } from "react"
import { useRouter } from "next/navigation"
import { Calendar, MapPin, Clock, Users, ExternalLink, Share2, Copy, Check, Zap, Mail } from "lucide-react"

const MomentumSharePage = () => {
  const [copied, setCopied] = useState(false)
  const router = useRouter()

  // Mock data - would come from URL params in real app
  const weekData = {
    week: "June 23-29, 2025",
    sharedBy: "Sarah Martinez",
    shareUrl: "momentum.thedscs.com/share?week=2025-06-23&user=sarah_m&token=abc123",
  }

  const weekEvents = [
    {
      id: 1,
      friend: "Alex Chen",
      title: "Late Night House Set",
      type: "DJ Gig",
      date: "2025-06-28",
      time: "10:00 PM",
      venue: "The Basement",
      location: "Brooklyn, NY",
      source: "Instagram",
      description: "Deep house vibes all night long 🎵",
      sourceUrl: "https://instagram.com/alexchen/post/123",
    },
    {
      id: 2,
      friend: "Maya Rodriguez",
      title: "Poetry & Wine Evening",
      type: "Reading",
      date: "2025-06-29",
      time: "7:30 PM",
      venue: "Vintner's Corner",
      location: "Oakland, CA",
      source: "Instagram",
      description: "Reading from my new collection, plus wine pairings",
      sourceUrl: "https://mayapoetry.substack.com/p/wine-reading",
    },
    {
      id: 3,
      friend: "Jordan Kim",
      title: "Natural Wine Pop-Up",
      type: "Pop-up",
      date: "2025-07-01",
      time: "6:00 PM",
      venue: "Corner Market",
      location: "San Francisco, CA",
      source: "Instagram",
      description: "Featuring biodynamic wines from small producers",
      sourceUrl: "https://jordankim.substack.com/p/wine-popup",
    },
    {
      id: 4,
      friend: "Sam Thompson",
      title: "Techno Underground",
      type: "DJ Gig",
      date: "2025-07-03",
      time: "11:00 PM",
      venue: "Warehouse 47",
      location: "Detroit, MI",
      source: "Resident Advisor",
      description: "Industrial techno set in raw warehouse space",
      sourceUrl: "https://ra.co/events/123456",
    },
  ]

  const addToCalendar = (event) => {
    const calendarUrl = `https://calendar.google.com/calendar/render?action=TEMPLATE&text=${encodeURIComponent(event.title)}&dates=${event.date.replace(/-/g, "")}T${event.time.replace(/[: ]/g, "").substring(0, 4)}00/${event.date.replace(/-/g, "")}T${event.time.replace(/[: ]/g, "").substring(0, 4)}00&details=${encodeURIComponent(event.description)}&location=${encodeURIComponent(event.venue + ", " + event.location)}`
    window.open(calendarUrl, "_blank")
  }

  const copyShareUrl = () => {
    navigator.clipboard.writeText(weekData.shareUrl)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const shareViaEmail = () => {
    const subject = `${weekData.sharedBy}'s Weekly Events (${weekData.week})`
    const body = `Hey! Here are the events I found for ${weekData.week}:\n\n${weekData.shareUrl}\n\nGenerated by Momentum - never miss your friends' events again!`
    window.open(`mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`)
  }

  return (
    <div className="min-h-screen" style={{ backgroundColor: "#FEFCF5" }}>
      {/* Header */}
      <div className="bg-white shadow-sm" style={{ borderBottom: "3px solid #1A1A1A" }}>
        <div className="max-w-4xl mx-auto px-6 py-6">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <div className="w-10 h-10 bg-gradient-to-r from-blue-800 to-blue-900 rounded-xl flex items-center justify-center">
                <Zap className="w-6 h-6 text-white" />
              </div>
              <div>
                <h1 className="text-2xl font-bold" style={{ color: "#1A1A1A" }}>
                  {weekData.sharedBy}'s Events
                </h1>
                <p className="text-sm" style={{ color: "#4A4A4A" }}>
                  Week of {weekData.week} • {weekEvents.length} events found
                </p>
              </div>
            </div>
            <div className="flex items-center gap-3">
              <button
                onClick={copyShareUrl}
                className="flex items-center gap-2 px-4 py-2 rounded-xl font-medium hover:opacity-70 transition-opacity"
                style={{
                  border: "2px solid #1A1A1A",
                  backgroundColor: "white",
                  color: "#1A1A1A",
                }}
              >
                {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
                {copied ? "Copied!" : "Copy Link"}
              </button>
              <button
                onClick={shareViaEmail}
                className="flex items-center gap-2 px-4 py-2 text-white rounded-xl font-medium hover:opacity-90 transition-opacity"
                style={{
                  backgroundColor: "#1E40AF",
                  border: "2px solid #1A1A1A",
                }}
              >
                <Mail className="w-4 h-4" />
                Email This
              </button>
            </div>
          </div>
        </div>
      </div>

      {/* Info Banner */}
      <div className="max-w-4xl mx-auto px-6 py-6">
        <div
          className="p-4 rounded-xl flex items-center gap-3"
          style={{
            border: "2px solid #1A1A1A",
            backgroundColor: "#F0F9FF",
          }}
        >
          <Share2 className="w-5 h-5" style={{ color: "#1E40AF" }} />
          <div className="flex-1">
            <p className="font-semibold" style={{ color: "#1A1A1A" }}>
              Shared Events List
            </p>
            <p className="text-sm" style={{ color: "#4A4A4A" }}>
              This is a read-only view. Want your own Momentum dashboard?
              <a href="/signup" className="font-semibold ml-1 hover:underline" style={{ color: "#1E40AF" }}>
                Sign up here
              </a>
            </p>
          </div>
        </div>
      </div>

      {/* Events List */}
      <div className="max-w-4xl mx-auto px-6 pb-12">
        <div className="space-y-6">
          {weekEvents.map((event) => (
            <div
              key={event.id}
              className="bg-white rounded-xl p-6 shadow-sm hover:shadow-md transition-shadow"
              style={{ border: "3px solid #1A1A1A" }}
            >
              <div className="flex items-start justify-between">
                <div className="flex-1">
                  <div className="flex items-center gap-3 mb-3">
                    <h3 className="font-bold text-lg" style={{ color: "#1A1A1A" }}>
                      {event.title}
                    </h3>
                    <span
                      className="px-3 py-1 text-xs font-bold rounded-full"
                      style={{
                        backgroundColor: "#FEFCF5",
                        color: "#1A1A1A",
                        border: "2px solid #1A1A1A",
                      }}
                    >
                      {event.type}
                    </span>
                    <span
                      className="px-3 py-1 text-xs font-bold rounded-full"
                      style={{
                        backgroundColor: "white",
                        color: "#4A4A4A",
                        border: "2px solid #4A4A4A",
                      }}
                    >
                      {event.source}
                    </span>
                  </div>

                  <p className="mb-4 font-medium" style={{ color: "#4A4A4A" }}>
                    {event.description}
                  </p>

                  <div className="flex items-center gap-6 text-sm font-semibold" style={{ color: "#4A4A4A" }}>
                    <div className="flex items-center gap-2">
                      <Users className="w-4 h-4" />
                      {event.friend}
                    </div>
                    <div className="flex items-center gap-2">
                      <Calendar className="w-4 h-4" />
                      {new Date(event.date).toLocaleDateString("en-US", {
                        weekday: "short",
                        month: "short",
                        day: "numeric",
                      })}
                    </div>
                    <div className="flex items-center gap-2">
                      <Clock className="w-4 h-4" />
                      {event.time}
                    </div>
                    <div className="flex items-center gap-2">
                      <MapPin className="w-4 h-4" />
                      {event.venue}, {event.location}
                    </div>
                  </div>
                </div>

                <div className="flex items-center gap-3 ml-6">
                  <a
                    href={event.sourceUrl}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="p-3 rounded-xl transition-opacity hover:opacity-70"
                    style={{
                      color: "#4A4A4A",
                      border: "2px solid #1A1A1A",
                      backgroundColor: "white",
                    }}
                    title="View original post"
                  >
                    <ExternalLink className="w-4 h-4" />
                  </a>
                  <button
                    onClick={() => addToCalendar(event)}
                    className="px-6 py-3 text-white rounded-xl text-sm font-bold hover:opacity-90 transition-opacity"
                    style={{
                      backgroundColor: "#1E40AF",
                      border: "2px solid #1A1A1A",
                    }}
                  >
                    Add to Calendar
                  </button>
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* Footer CTA */}
        <div
          className="mt-12 p-8 rounded-xl text-center"
          style={{
            border: "3px solid #1A1A1A",
            backgroundColor: "white",
          }}
        >
          <h3 className="text-xl font-bold mb-3" style={{ color: "#1A1A1A" }}>
            Want to track your own friends' events?
          </h3>
          <p className="mb-6" style={{ color: "#4A4A4A" }}>
            Momentum automatically finds events from Instagram and Resident Advisor so you never miss out.
          </p>
          <button
            className="px-8 py-4 text-white rounded-xl text-lg font-bold hover:opacity-90 transition-opacity"
            style={{
              backgroundColor: "#1E40AF",
              border: "2px solid #1A1A1A",
            }}
          >
            Get Started for Free
          </button>
        </div>
      </div>
    </div>
  )
}

export default MomentumSharePage
